# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Reem Alzahrani"
description: > # this means to ignore newlines until "email:"
   An aspiring AI researcher

email: raalzahrani65@gmail.com
#blog logo
logo: "/assets/images/rlogo.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/wallpaperflare.com_wallpaper2.jpg"

name: 'Reem Alzahrani'
author: 'Reem Alzahrani'
author_image: "/assets/images/rlogo.jpg"

paginate:	5

url: "https://raalzahrani.github.io/" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@reemalzahrani65'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/reemalzahrani65
    desc: Check my twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/raalzahrani
    desc:	Check my github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
